### ISSUE TITLE
Occasional news releases with new specs/proposals/etc

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3.github.io#103]
This was brought up again recently, just like a news tab on the site with a simple RSS feed to announce changes to interested people. Could be cool to look at doing, would probably throw it on the WG page to improve #83 as well.

**Comment by Zarthus** [comment]
a status page on the front page with a list of specs and the current status would be nice as well

**Comment by DanielOaks** [comment]
Solved by #115
