### ISSUE TITLE
Add testnet info to the site as well

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3.github.io#105]
Makes it much easier to test specs if people know a test network that supports them. Add some sort of testnet indicator to each server (if it has one), and mark it somewhere appropriate.

**Comment by DanielOaks** [comment]
This could be integrated into a wider just listing network info in general.

One section for test networks, next section for real networks.

**Comment by ChickenNuggers** [comment]
Thoughts on formatting as a table:

## Test Networks

| Server | Software | Address |
|--------|--------|--------|
| InspIRCd Test Server | InspIRCd | testnet.inspircd.org |

## Other Networks

| Server | Software | Address |
|--------|--------|--------|
| Freenode | ircd-seven | irc.freenode.net |

**Comment by Zarthus** [comment]
seems like this issue is implemented?

**Comment by DanielOaks** [comment]
Yep, all done! Thanks
