### ISSUE TITLE
Restrictions of networks to add to the network page

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3.github.io#116]
So we obviously want some sort of limit, so we don't end up with 9000 random networks on there. Things like number of clients, activity, whether they're a top100 network and such come info it.

Where do we wanna set the limits here, and which sort of networks do we want on that page? What is most useful for end users?

I feel like the networks page answers two questions:

1. Where can I go to test my IRCv3 client implementation? (testnet section)
2. Do many real-world networks implement IRCv3 stuff? (real-world section)

What do we think here?

**Comment by DanielOaks** [comment]
As a note here, if anyone wants to make an argument without like, putting their name to it or anything (since it can be a bit of a touchy subject, particularly when you start mentioning network names), throw me a PM/email and I can throw it here for you.

**Comment by Zarthus** [comment]
Do you want to maintain the current way of viewing networks (one relatively big list with a lot of information), or - if this gets traction, provide a better way to view the existing lists? With the current situation, I can't imagine there being room for more than 20 networks.

If you're going by a top 100, you're saying the theoretical possibility of there being 100 networks on that list exists, which would make opening and viewing that page a bit of a pain.

Provided someone can think of a good way to handle it, and spend time developing it, perhaps a way to group entries by ircd might be preferable for viewing (when testing out capabilities, you'd want to test cross-network performance (bullet point 1), while still maintaining a list of just network names that implement ircv3 (bullet point 2) - something like http://i.imgur.com/zvuDMOz.png -- note that the image was made in 3 minutes work and there can be put more thought in it, but the basic idea is to allow the displaying of more lists while still listing all networks. Some javascript will probably be involved. 

If that idea is liked, you have more wiggle room for limits than the current situation offers.

If you're going to keep the current way of displaying networks, I'd pick some arbitrary limits to hold on to to ensure the list doesn't fill up and serve first-come first-served, and only add networks that bring something new to the table (which still leaves you with a poor long-term solution).

**Comment by ChickenNuggers** [comment]
I actually wrote something like this for a different project a while back. It'd definitely be doable with <~30 lines of JavaScript.

**Comment by DanielOaks** [comment]
I think that the way we're doing it currently makes a lot of sense. Gives a good overview for specific caps, which I feel is more the focus point of all these support pages. However, if there's a better way to format it then I'm definitely open to suggestions (even if it's just a roughly sketched-out image and we can work our how to implement it later.

I can see what you mean with splitting it by IRCd, but I feel like that splits it up in ways that we don't necessarily want to split them up, and emphasizes something we don't necessarily want to. Definitely feel free to keep iterating and looking at it though, I'm curious to see what we can do here.

By 'top 100', I mean restricting it to roughly 'networks that could be in [this list](http://irc.netsplit.de/networks/top100.php)'. The upside about restricting it in this way is that it'll include nets that users should know, which answers Q2 up there a lot better, and a point that's been made.

But this isn't set in stone, and exactly what that page is meant to represent, the q's it's meant to answer and what it's meant for aren't set in stone yet, discussion encouraged on that front.

**Comment by Zarthus** [comment]
If you don't think the page is in need of any visual enhancements beyond what we already have, I'd say going over pull request items case-by-case is probably the best solution. No need for limits, you'll reach that conclusion eventually. Only soft-criteria I'd definitely keep in is the top100 list.

**Comment by SaberUK** [comment]
Rather than "top 100" wouldn't it be better to limit based on number of users/channels?

**Comment by DanielOaks** [comment]
Yeah... the way I use 'top 100' here means fairly heavily restricting it to nets that people generally know, are widespread and/or are recognised.

Maybe just soft-limiting it to ~150 users minimum for now, and we can discuss it further as we go?

**Comment by DanielOaks** [comment]
yeah we'll just be doing something like this for now (and evaling on case-by-case basis), should be fine
