### ISSUE TITLE
Add separate support list for ircd-seven

### ISSUE THREAD

**Issue by jwheare** [ircv3/ircv3.github.io#151]
Charybdis is no more: https://github.com/charybdis-ircd/charybdis/commit/40ac82e87820d9941bdd38571d0390122008e5d3 and points to http://github.com/freenode/ircd-seven as a replacement, which doesn't support the same extent of CAPs. Freenode is already listed on the networks support tab, but I think adding ircd-seven to the server list would make sense. Should be a straightforward copy pasta.

**Comment by DanielOaks** [comment]
Let's leave it for a month or so to see how it resolves (as it seems like there was a release after / around when that was posted) and just add `dead: true` to the yaml for it for now.

**Comment by jwheare** [comment]
Sure, 3.5 had a release, just looks like 4+ won't happen. But I'm not saying we should remove Charybdis for now, just add an extra server to the list for ircd-seven because it's lagging quite far behind.

**Comment by jwheare** [comment]
4 seems back on track, but issue still stands: https://github.com/charybdis-ircd/charybdis/commit/be9fb5ac00f03b2a7a0fe954a0f0166d95ce7865

**Comment by DanielOaks** [comment]
We won't add a support list for ircd-seven, will make a new issue about this server family though.
