### ISSUE TITLE
Text is far too dense to read

### ISSUE THREAD

**Issue by prawnsalad** [ircv3/ircv3.github.io#154]
Setting `.page-header { line-height: 1.5; }` and `.content { line-height: 1.5 }` makes everything far easier to read.

**Comment by prawnsalad** [comment]
Before:
![image](https://cloud.githubusercontent.com/assets/725880/24983643/5e2cd110-1fe0-11e7-864a-5407f53d804e.png)


After: 
![image](https://cloud.githubusercontent.com/assets/725880/24983666/8a2be454-1fe0-11e7-82b1-ba9862924331.png)

**Comment by MuffinMedic** [comment]
Seconded. "After" looks much better.

**Comment by DanielOaks** [comment]
Thanks for the yell! I'll take another look at the line height, see what works best.

**Comment by DanielOaks** [comment]
Thanks for the yell with this! I've bumped it up to 1.4 now since 1.5 makes the site text look a bit too disjointed for me. The new line height should provide a nice balance between readability and looks.
