### ISSUE TITLE
Navbar element with dropdown shifts when you hover over it

### ISSUE THREAD

**Issue by Zarthus** [ircv3/ircv3.github.io#165]
![video](https://lynvie.com/~zarthus/video.mp4)
https://lynvie.com/~zarthus/video.mp4

Only happens when the element is active, e.g. you're on http://ircv3.net/support/networks.html

**Comment by Zarthus** [comment]
While possibly related to https://github.com/ircv3/ircv3.github.io/issues/148, I don't think they talk about the same issue due to that being about tables. and this is a list

**Comment by DanielOaks** [comment]
Thanks for the yell with this! I've corrected this for all relevant navbar items.
