### ISSUE TITLE
Some software is listed in IRCv3 compliant software without even IRCv3.1 base compatibility

### ISSUE THREAD

**Issue by Mikaela** [ircv3/ircv3.github.io#17]
The base requirements for 3.1 are cap, multi-prefix and sasl. The following software doesn't fill the requirements:

## Clients

* BitchX (multi-prefix)
* Konversation (multi-prefix, sasl)
* LimeChat (multi-prefix)
* mIRC (multi-prefix, sasl)
* Mibbit (multi-prefix, sasl)
* AndChat (multi-prefix)
* AndroIRC (multi-prefix)
* IRC7 (multi-prefix)
* LimeChat mobile (multi-prefix)

## Servers

* IRCCloud (sasl)
* mammon-ircd (multi-prefix, sasl)

## Libraries

* Net::Async::IRC (extended-join, multi-prefix)

**Comment by DanielOaks** [comment]
Looking at a different way to display non-conformant software. Will go through some ideas and post once I've got something that looks decent

**Comment by jwheare** [comment]
12:43 @Mikaela no access to github at the moment and my only complaint against not base compatible cöients is resolved by that PR (#35) when it gets merged

This issue can be closed.
