### ISSUE TITLE
Software: could base requirements be bolded (e.g. cap and all yes/no below it)

### ISSUE THREAD

**Issue by Mikaela** [ircv3/ircv3.github.io#18]
I think some kind of formatting would make it more clear what clients are required to have in order to be IRCv3.1 compatible.

**Comment by Mikaela** [comment]
Actually having the whole line bolded would help me with seeking https://github.com/ircv3/ircv3.github.io/issues/17.

**Comment by Mikaela** [comment]
I mean `cap` bolded and all yes/no under it and same with other base extensions.

**Comment by DarthGandalf** [comment]
Or group these columns in the left and separate from the rest by more think vertical line.
