### ISSUE TITLE
Add RSS link tag to head

### ISSUE THREAD

**Issue by rakiru** [ircv3/ircv3.github.io#182]
The feed is linked in the footer, but ideally it should also be linked in the `<head>` to allow autodiscovery by browsers, feed readers, etc. Something like:

    <link rel="alternate" type="application/rss+xml" href="/feed.xml" />

**Comment by DanielOaks** [comment]
Thanks, added in c8e3f6215eb3c1596e074d4b01fa8c69b9bf5f30!
