### ISSUE TITLE
Software: Specify OS support for clients

### ISSUE THREAD

**Issue by Mikaela** [ircv3/ircv3.github.io#20]
At #znc it was asked if there is any good Android IRC app which works well with ZNC and I replied:

> any from http://ircv3.net/software/clients.html that supports server-time, I would say
> it doesn't separate by mobile OS though
> none it looks like

I think that especially with mobile the OS should be indicated somehow, but it wouldn't hurt with others either, it just must be kept in mind that clients can support multiple OSes.

**Comment by attilamolnar** [comment]
I don't think we should do this. The IRCv3 site is not an IRC help site and is certainly not a client guide for users, it's mainly aimed at developers.

**Comment by Mikaela** [comment]
There is already list of clients and what capabilities they support which probably interests more IRCv3-enthustiastic users than developers and is also the place where people link when someone asks for good IRC client. If the list didn't exist, users are discouraged from using IRCv3 capable clients and client is easier to find when you know one for your OS.

**Comment by attilamolnar** [comment]
Implemented by @DanielOaks in #36.
