### ISSUE TITLE
Don't show WebIRC where not applicable

### ISSUE THREAD

**Issue by jesopo** [ircv3/ircv3.github.io#204]
e.g. `/software/clients.html` shows it on all tables where it only actually makes sense for the `Web Clients` table.

> **dan-**: makes sense for them only to be on the webclient one methinks, or something similar. one main purpose of the support page is to find software that implements XYZ so you can test using it, so it should stay on there... just not for all clients, esp when none of them implements a thing
>  **dan-**: will likely take a bit of liquid updates to the table include tho
>  **dan-**: specific attribute on certain specs that allow for it to be dropped from support tables if no s/w supports it, because I don't want that by standard (discourages new spec adoption), though we can steal the handling of the draft specs because that's the default behaviour for those
>  **dan-**: etc

**Comment by jesopo** [comment]
Unless I'm wrong, the tables already do this for draft specs? can't we just extend the "only show this line if something in the table supports it" logic fairly easily?

**Comment by DanielOaks** [comment]
Now done as of 1b8e97e7d90b89cb2a47f36c12c7b17ca471391b.

Generally, we now have a method to say 'don't show this row in a support table if no software in that table supports the feature', may be useful in other places for more specific specifications.
