### ISSUE TITLE
Abandoned software should be removed from the support tables

### ISSUE THREAD

**Issue by SaberUK** [ircv3/ircv3.github.io#221]
There's a bunch of clients and servers in the support tables which haven't been maintained in years. We should probably remove them.

## Desktop Clients

- Colloquy &mdash; last release almost five years ago, last commit 19 months ago. 

## Web Clients

- Iris &mdash; last commit over two years ago, marked as legacy on GitHub.

## Mobile Clients

- AndChat &mdash; website link dead, removed from Google Play according to /r/irc.
- IRC7 &mdash; website link dead, WP7 no longer a thing that exists.

... plus probably a bunch more that I can't investigate

## Servers

- ChatIRCd &mdash; website link dead, no commits in over a year.
- Elemental IRCd &mdash; no commits in over two years.
- mammon-ircd &mdash; no commits in over three years.

**Comment by jwheare** [comment]
I'd save Colloquy, it's probably the best completely free native gui irc client for mac.

**Comment by SaberUK** [comment]
#223 has been merged, closing.
