### ISSUE TITLE
add new message tags row to support table?

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3.github.io#231]
So we've now merged the new merged [Message Tags spec](https://ircv3.net/specs/extensions/message-tags.html). Awesome, cool, all good.

So previously (when the `message-tags` 3.3 spec was just a draft), the support row very specific referred to support for the `message-tags` capability (since it was prefixed by draft/ and all, showing as `draft/message-tags-0.2`).

Now that the `message-tags` capability is presented as a part of the core Message Tags spec, it makes things a little difficult. With ratifying the new version, I've changed the row name from `draft/message-tags-0.2` to `message-tags cap` (seen [here](https://ircv3.net/software/servers.html)). For what it's worth, I think making this change and leaving it here is the best way to go with it, it's very clear what a green/red on the row means, and I don't think a general 'tag support' row would be useful for devs. But people have discussed whether including a separate, more general row that just indicates 'supports tags/tagging at all' would be useful.

Specifically, I think that a project 'supports tags' can be better indicated by the existing rows which show support for specs that define and use specific tags. The only way it feels like a 'supports tags' indicator could be useful is for devs looking to hack on a new project and seeing which ones support general tag functionality already that they could extend? I dunno, it doesn't feel like a very useful bit of information to have on there, whereas showing the `message-tags cap` support indicates support for TAGMSG and c2c tags, which are definitely of interest to devs.

Thoughts appreciated!

**Comment by jwheare** [comment]
I think change the row name to just `message-tags`, drop the "cap" it already refers to the cap name, just like the other caps. Indicating support for a client supporting tags without that cap should just be done by marking `server-time` etc as green. It's not really that meaningful.

**Comment by DanielOaks** [comment]
Sounds good, I can do that and change the title text to make clear it refers to the capability

**Comment by DanielOaks** [comment]
5abae2845faac38854eea846faaf73560f418994 resolves this, whoo!
