### ISSUE TITLE
on specifications themselves: a footer which shows which software(s) implement the spec

### ISSUE THREAD

**Issue by Zarthus** [ircv3/ircv3.github.io#234]
Something like this in the footer of every specification (with a bit better wording) so it's easy to find what you can test on/with and widespread support for a SPECIFIC spec, rather than just looking at the support table and manually comparing when you're just interested in one thing

![img](https://liefland.net/~zarthus/image/chrome_841f64cf72fa.png)

**Comment by DanielOaks** [comment]
Now done as of 6e3c0081a215ad91e39f4b7349e553bc627e7460. If you value your sanity you will not look into exactly how it works
