### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [ircv3/ircv3.github.io#240]
The official website doesn't support IPv6.

Since it seems to use Netlify, it should suffice to follow [the instructions on their IPv6 support announcement](https://www.netlify.com/blog/2018/11/26/announcing-ipv6-support-on-the-netlify-application-delivery-network/#are-we-there-yet) for enabling it.

**Comment by DarthGandalf** [comment]
Thanks for heads up, I missed their announcement.

Despite they saying that it should be all automatic, I needed to click the "Enable IPv6" button in Netlify. It should start working when DNS propagates, I guess.

**Comment by tambry** [comment]
Working now. Thanks!

As far as I understand IPv6 support was enabled automatically only for CNAME-based configurations (which `ircv3.net` isn't).
