### ISSUE TITLE
ircv3.org vs ircv3.net

### ISSUE THREAD

**Issue by levifig** [ircv3/ircv3.github.io#33]
Both the _config.yml (though commented) and the GitHub organization URL indicate http://ircv3.org as being the official domain, though that domain doesn't resolve. It seems the official TLD is .net, not .org.

Is this so or am I missing something? :)

**Comment by SaberUK** [comment]
Are you using Google DNS? .org redirects to .net but it seems that Google DNS is broken for some reason.

```
SaberUK@Kirika5287:~/Projects/irc/inspircd/packages$ nslookup ircv3.org 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find ircv3.org: SERVFAIL

SaberUK@Kirika5287:~/Projects/irc/inspircd/packages$ nslookup ircv3.org 208.67.222.222
Server:		208.67.222.222
Address:	208.67.222.222#53

Non-authoritative answer:
Name:	ircv3.org
Address: 192.30.252.154
Name:	ircv3.org
Address: 192.30.252.153
```

**Comment by levifig** [comment]
Yup, using Google DNS. :o That is beyond strange…

**Comment by Mikaela** [comment]
Has anyone contacted Google DNS on the issue?

* https://groups.google.com/forum/#!forum/public-dns-discuss

**Comment by SaberUK** [comment]
The DNS problem should be fixed now. The domain registrar (Hover) were being incompetent with regards to DNSSEC so I have transferred to a new registrar and it seems to be working now.
