### ISSUE TITLE
Technical board membership and processes

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3.github.io#350]
The technical board's stayed largely the same for a fair while now. So have the processes that IRCv3 has worked with. Figured I'd make an issue to discuss that (just opening it in this repo because this is where previous TB membership has been discussed in the past).

---

So, what other projects make sense to bring onto the TB? Or are there any irc-related people who've been doing stuff actively that people think we should bring on?

Obviously, Atheme (iirc last time we chatted to them we couldn't come to agreement on who to be put forward to represent them), networks are always useful so maybe someone representing solanum and/or one of the networks that're putting work into that project? They're both really big, obvious hitters, who else has been active and pushing development?

In general, more network involvement would be appreciated I think - but aside from freenode a lot of the other big networks seemed not-that-interested in working with us because of previous bad experiences in years past. Should we reach out again? If so, who should we reach out to.

I know that I've been really inactive, and sling's been doing more than me in terms of pushing stuff towards v3?

---

Somewhat of a side discussion, given the lack of real 'power' that TB membership brings (there's the perceived power of course, but in terms of process it's more limited and I think we tend to be pretty lax in terms of most parts of the process that require 'actual authority'), I find that most of the time when people ask for TB changes what people are really looking for is a change in the processes the group runs with.

In https://github.com/ircv3/ircv3-specifications/pull/375 (or along with when I was writing up that PR) I was really messing about with changing up our processes in general, overhauling them to make them more defined or to try and speed up useful, active development. Lately I've been a lot more bent on the idea of implementors getting together to build ideas, prove they work, and then submitting them to us once they're ready and running (ala znc with server-time, irccloud with the client-tags they introduced, etc). Anyone have ideas about changing processes or ideas to improve them, or itches/issues they have with the current processes v3 works under?

**Comment by jesopo** [comment]
I'd like to suggest we look at reinstating meetings with set times and agendas

**Comment by DanielOaks** [comment]
Regarding processes, https://github.com/ircv3/ircv3-specifications/pull/215 and https://github.com/ircv3/ircv3-specifications/issues/214 are I think the last places we explicitly discussed our processes around things getting ratified.

**Comment by DanielOaks** [comment]
Proposal to have a meeting, and possibly to regularly schedule ones in the future. Can't magically bring everyone back into activity, but can motivate people into doing things (like our informal meetup at #live a few years ago did). It can also unstick decisions where everyone's just waiting for someone else to say something, and to get quick reads over everyone's thoughts on specific proposals/PRs/etc.

We could make them TB-only or require TB members to be there, but that'd make the meetings an extra responsibility that may put people off (seems counter to the 'get more diverse range of opinions in the WG/TB' idea above). We could go for voice/video meetings, but given our membership that probably wouldn't work too well. So I think just something along the lines of _"Meeting will happen in the IRCv3 channel at XYZ time"_ would work best. We'll probably want some basic rules to follow, just simple things so we can stay on-task, run through all the agenda items we want to, and finish in an appropriate amount of time.

We may use Doodle or framedate.org to organize it - in the past I've found https://www.worldtimebuddy.com/ pretty useful for working out timezones with different people but yeah, whatever works. Might want to collect email addresses of TB members to send details out if we schedule more meetings in future? And/or of parties interested in meetings generally? Or maybe we can just announce it here and in the channel and worry about all that later on.

Rough agenda:
- Go through the roadmap, check where we are on each issue.
  - See any issues/blockers/future work on issues.
  - Go through specs that've been kicking around for ages without any resolution, decide on how to resolve them or what work needs to be done to resolve them one way or another.
- Discuss how to fix the technical board to make people feel better about the WG process (I suspect this might be a more abstract discussion, but any concrete proposals from this issue could probably be discussed in particular).

**Comment by jwheare** [comment]
opened #353 to plan times
