### ISSUE TITLE
List information for services packages

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3.github.io#49]
As mentioned in #48, it would be nice to see information for services packages.

I'm not sure how much use services packages have for the various IRCv3 specifications (since they usually use an S2S protocol, probably a lot of things they don't care about), but at least for things like SASL support it would be very useful.

**Comment by Mikaela** [comment]
:+1: as I started wondering about SCRAM-SHA-256 and if anyone supports it and such table could tell it to me immediately.

**Comment by SaberUK** [comment]
> I started wondering about SCRAM-SHA-256 and if anyone supports it 

Nobody does currently but Anope will soon when I finish writing the module for it.

**Comment by DanielOaks** [comment]
I'll consider this done for now.
