### ISSUE TITLE
Mark DH-* SASL specs as deprecated and such

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3.github.io#50]
On the DH-* SASL documentation pages, there should be a bit warning saying they're deprecated, etc. Honestly I'm surprised this isn't done already.

This would probably be best implemented as something along the lines of a `deprecated: true` in the YAML front matter of the actual spec files and the addition of an if statement in the `spec` layout.

**Comment by attilamolnar** [comment]
This has been addressed in ircv3/ircv3-specifications#218.

**Comment by DanielOaks** [comment]
This is not yet actually implemented on the web side, should be done in the next day or two now that it's finished on the spec side.

**Comment by DanielOaks** [comment]
Fixed by https://github.com/ircv3/ircv3.github.io/commit/97ad63a963f943d4425b76cd2e72e48b2d9d7981
