### ISSUE TITLE
Improve the site overall

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3.github.io#64]
This is a very general issue. Basically, we need to do some overhauling on the front page and some of the other pages to present ourselves and the work we're doing more clearly. Basically, to show people _why_ they should be involved and/or keeping an eye on us, the sort of features IRCv3 specifications provide and what we're working on, that sort of thing.

We have multiple audiences, and we should see who we really want to and need to cater to, and tailor the parts of our site to that.

This is probably gonna be a fairly decent overhaul to the site. We should keep #9 in mind as part of it.

**Comment by Mikaela** [comment]
Possibly offtopic for this issue, but having the site over https would be nice. It just seems weird that encryption is recommended (HSTS (if we ignore https://github.com/ircv3/ircv3-specifications/issues/207)), but the site is only accessible with http.

*I am fully aware of the site being on GitHub pages and thus not being able to have TLS as it uses custom domain.*

**Comment by DarthGandalf** [comment]
Yes, it's offtopic. Please open a separate issue for that if you want that
feature.

2016-02-01 14:15 GMT+00:00 Mikaela Suomalainen <notifications@github.com>:

**Comment by DanielOaks** [comment]
Alright, so here are some roughish mockups of a new homepage/WG page.

---

I think this home page is better suited to those who aren't already a part of the IRCv3 WG, giving them a quick rundown of who we are, what we do, and where to find more info.

There are also the lists underneath it, features that our specs provide for people to see some more concrete reasons for why to look info IRCv3, "working on" for the sort of things our participants are doing and looking into, and finally a list of participating orgs for people to see who we have participating in the working group.

I think it gives us a cleaner, more concrete 'brand' in the eyes of networks or users who visit that page, better answering why to look into our specs and what they can provide.

The graph up the top slowly moves about, just showing some movement and being visually interesting without taking too much attention away from the rest of the site. An online version of this page can be accessed right now [here](http://danieloaks.net/ircv3-site/) (there are some issues with Mobile concerning the graph, ignore that right now, mockups etc).

![Home Page](https://cloud.githubusercontent.com/assets/251281/12740609/7cfb4f4e-c9c0-11e5-9b52-62246c1a9032.png)

---

The Working Group page is basically where most of the current home page got moved to. It contains links to our specs, information on participating, and our Github repo. I think this is pretty good for people who either want more info on the working group, or want links to things like our specifications.

The specifications page will probably be modified or redone as part of #9, so that's not a big concern right now with these mockups.

An online version of this page can be accessed right now [here](http://danieloaks.net/ircv3-site/wg.html).

![Working Group Page](https://cloud.githubusercontent.com/assets/251281/12740672/28a60c08-c9c1-11e5-8a84-211af6d92793.png)

**Comment by ChickenNuggers** [comment]
FWIW I liked the new site. It's better organized. Also, @DanielOaks and I were thinking about (re)implementing a contributors / stockholders list, which will eventually/hopefully be included.

**Comment by Mikaela** [comment]
I like those mockups with the exception of this part.

* ![this part](https://i.imgur.com/GAYDa7s.png)

**Comment by DanielOaks** [comment]
Which part don't you like about it? The colours of the `STATS` text there is dodgy, but I'll override that with a special monospace colour scheme for inside those blocks. The `[link]` tags and such at the end of the lines irks me, but I'll be playing with those to see if I can integrate them more nicely and cleanly.

**Comment by Mikaela** [comment]
The `STATS` background and text colour being completely out of place when compared to the rest. The red also is a little hard to see with this display in my opinion.

**Comment by DanielOaks** [comment]
Alright, got some new mockups.

I think splitting these pages up into an explicit landing page and working group page lets us better serve the people who pop onto the site for the first time. While they may not look that different, I think the language used and what's linked to on each page better suits first time viewers vs people specifically interested in the Working Group.

---

As said before, I think this landing page is more appropriate for those not already a part of the IRCv3 WG. It gives them a general overview of who we are, what we do, and some reasons why they should look at us and keep an eye on the work we're doing.

Decided to junk the graph, as others mentioned it didn't serve a clear purpose and the design was made stronger by removing it.

![IRCv3 Landing Page](https://cloud.githubusercontent.com/assets/251281/12848083/5a258444-cc63-11e5-8b1c-5d973310c14d.png)

---

The Working Group page is the same as it was before, basically the old homepage. This gives people a good overview of the work we're doing, our resources, and how to contribute / be a part of the working group.

![IRCv3 WG Page](https://cloud.githubusercontent.com/assets/251281/12848135/af829a26-cc63-11e5-9263-0ed21c329cab.png)

**Comment by ChickenNuggers** [comment]
I'm not really a fan of having all that information shoved to the bottom; a lot of people prefer for information to be towards the top of the page. Perhaps we could put the IRCv3 features and below information, above the "View" links?

**Comment by DanielOaks** [comment]
The only way *all* of that information would go up there is if it was in some sort of a slider, which has already been rejected. This is because the "view" links are extremely important, and having them underneath all that content almost ensures that they won't be clicked. Maybe some subset, such as just the features, could be thrown above there, but I'll need to do further experimenting to see how that looks.

Really, it's just deciding which information should be towards the top. I think the tagline and the various view links are the most important thing, and that dark-green box does show on the bottom of the page for most desktop resolutions, headed by "IRCv3 Features", which convinces people to scroll down and take a look if they're interested.

**Comment by DanielOaks** [comment]
I can consider this done for now, more specific issues addressing specific parts.
