### ISSUE TITLE
Secure connection to ircv3.net

### ISSUE THREAD

**Issue by Mikaela** [ircv3/ircv3.github.io#66]
At https://github.com/ircv3/ircv3.github.io/issues/64#issuecomment-177989604 I said:

> Possibly offtopic for this issue, but having the site over https would be nice. It just seems weird that encryption is recommended (HSTS (if we ignore https://github.com/ircv3/ircv3-specifications/issues/207)), but the site is only accessible with http.

> *I am fully aware of the site being on GitHub pages and thus not being able to have TLS as it uses custom domain.*

And @DarthGandalf replied:

> Yes, it's offtopic. Please open a separate issue for that if you want that
feature.

**Comment by ChickenNuggers** [comment]
Unless we (in general) move to a custom server host or use something like CloudFlare's DNS, I don't think this is possible.

**Comment by attilamolnar** [comment]
We cannot do anything about this. As long as the site is hosted on github we have the limitations they impose on secure connections. Please bug github about this. I'd like to close this issue as it doesn't help us any and takes attention away from issues that we can do something about.
