### ISSUE TITLE
Members list on the website

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3.github.io#67]
We have the Google Docs stakeholders list [here](http://goo.gl/85s9NS).

Do we want to throw that onto the website, on the Participants page or something? Or would it be best to mostly leave it at organisations involved with us on the site and leave that as an 'administrative' document?

**Comment by ChickenNuggers** [comment]
http://pb.i0i0.me/p/raw/CixdTydl

There's a YAML document with all the stakeholders as of February 11

**Comment by DanielOaks** [comment]
This would probably come along with https://github.com/ircv3/ircv3-specifications/pull/215 and the tightening up of the stakeholder requirements that come along with it, but thanks very much for that document, will definitely be useful!

**Comment by ChickenNuggers** [comment]
Something like:

```
{% for stakeholder in stakeholders %}
<name>{{ stakeholder.name }}</name>
<project>{{ stakeholder.project }}</project>
<github>{{ stakeholder.github }}</github>
{% endfor %}
```

should work for automatic generation, modifying the YAML data to have it called "stakeholders" or however that works.

**Comment by SaberUK** [comment]
:+1: for importing to the website.

**Comment by DarthGandalf** [comment]
LGTM

Nit: I'd replace "name" with either "irc" or "freenode"

**Comment by ChickenNuggers** [comment]
@DarthGandalf The reason I chose name is it didn't specify what it actually was; the column head says "col" but if that's what it's purpose is, that's fine.

**Comment by DanielOaks** [comment]
Coolcool, I'll play with this to get it looking nicely and submit a PR once I'm happy with it. Just using that list above, until/otherwise stakeholder stuff happens with the org in the meantime.

**Comment by ChickenNuggers** [comment]
@DanielOaks ... @kaniini is missing charybdis in that list. Don't know why it wasn't there.

**Comment by DanielOaks** [comment]
Changed 'Stakeholders' to 'Members' to work along with the new governance stuff.

**Comment by DanielOaks** [comment]
Actually, we'll stall this issue for now and revisit it later. The governance and technical board lists and such are more important issues that may even remove the need for this list.

**Comment by ChickenNuggers** [comment]
So http://ircv3.net/participation.html just says that participation in the WG is as simple as contribution to the repositories here, or software that supports IRCv3. I doubt a list that long would be reasonable.

**Comment by DanielOaks** [comment]
Yeah that participation page is essentially just a rough list of peeps that contribute. You'll notice it's also on the main homepage, down the bottom: http://ircv3.net/

That participation list is essentially just so that people can take a look and get a rough idea of who contributes to this, the projects and nets they know that are a part of IRCv3. That list is relatively open, just informally limited to 'things people should recognise'.

**Comment by ChickenNuggers** [comment]
The point is, there's almost no minimum requirement - based on what's posted on that page - on who is allowed to join. The "members list" might as well be just the list of contributors and people who've PR'd using the GitHub UI.

**Comment by DanielOaks** [comment]
Essentially that's what it is, yeah. That list is intentionally informally decided just based on people/projects that want to be added, since codifying requirements for it are fairly difficult. Since it's based on just whether we (as a group) think they should be on there or not rather than any specific requirements, I'm not sure we can specify it any further.

As an aside, if someone's a part of a project they want added there, feel free to yell in here or at me and should go well.

**Comment by ChickenNuggers** [comment]
:( my list was deleted from the paste service. guess i'll be remaking that Soon(tm).

**Comment by ChickenNuggers** [comment]
Also, to note, https://github.com/ircv3/ircv3.github.io/graphs/contributors?from=2015-04-19&to=2016-11-19&type=c and https://github.com/ircv3/ircv3-specifications/graphs/contributors?from=2015-04-19&to=2016-11-19&type=c is probably where I'd get the initial list.

**Comment by DanielOaks** [comment]
Aside from maybe an update to lists I think this is fine. Anyone wants changes here, feel free to throw stuff at me, the chan or just submit PR. Otherwise, should be cool for now.
