### ISSUE TITLE
Pages could have meta descriptions

### ISSUE THREAD

**Issue by Mikaela** [ircv3/ircv3.github.io#7]
* https://encrypted.google.com/search?q=site:ircv3.net

That search doesn't tell a lot about what IRCv3 is and most of meta descriptions are just `IRCv3 development community.`

They can be added by adding `excerpt: "meta description here"` in the YAML frontend matter or whatever it was called as.

**Comment by attilamolnar** [comment]
Implemented by @DanielOaks in #37.
