### ISSUE TITLE
Add shout to table

### ISSUE THREAD

**Issue by davelab6** [ircv3/ircv3.github.io#72]
http://ircv3.net/software/clients.html is missing http://shout-irc.com which is a pity because its great

**Comment by davelab6** [comment]
cc @erming

**Comment by dequis** [comment]
As far as I can see it has no support for ircv3 stuff at all. Open an issue in their tracker first and once they have something implemented on their side submit a pull request editing `_data/sw_clients.yml`

**Comment by DanielOaks** [comment]
Hi! Yep, when it supports some number of our [specs](http://ircv3.net/irc/), we'd be glad to add it to the support table. You can either submit a PR or ask us to add it to the table once it supports something.

**Comment by davelab6** [comment]
Sure, thanks guys
