### ISSUE TITLE
pydle has a release package with some 3.2 support now

### ISSUE THREAD

**Issue by ayust** [ircv3/ircv3.github.io#78]
pydle just cut 0.8.2 from HEAD (https://github.com/Shizmob/pydle/commit/36f4711566db55d41cd07b784d1d66859992215c), so the items which are currently listed as `git` support can probably be updated.

**Comment by jwheare** [comment]
CAP NEW and DEL don't seem to be supported, so I changed CAP 3.2 support to partial with a note.
