### ISSUE TITLE
Software should list IRC protocol versions supported

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3.github.io#8]
Since we now have 3.1 and 3.2, we should be listing which version of the spec software packages support.

Suggested by @Mikaela, in response to the confusion in https://github.com/znc/znc/issues/960

It's been suggested that this should contain more information about what specific features, specifications, and extensions are supported for each software package. A dropdown / collapsible element listing would probably work – I'll have a play about with this.

**Comment by Mikaela** [comment]
Without having any webdev skills,  I think specifying all supported capabilities separately would be difficult and what if different capabilities are started to be supported in different versions?

Now that I type this, the answer to latter would probably mention the lowest version that supports all capabilities?

**Comment by DarthGandalf** [comment]
Or a matrix, similar to http://en.wikipedia.org/wiki/Comparison_of_wiki_software#Features_1

**Comment by DanielOaks** [comment]
I was thinking the same, @DarthGandalf

I'm experimenting with this over here: http://danieloaks.net/ircv3-site/software/servers.html

**Comment by DanielOaks** [comment]
This is almost good to go, got supported feature information from most of the clients and servers on that list (though for most, it's just a Yes/No instead of a version number). I'll run around and contact the last few, check the info, then it should be fine to push to the site proper.

If you have any comments, updates, etc, post them in here.

Temporary, development preview pages: [clients](http://danieloaks.net/ircv3-site/software/clients.html), [servers](http://danieloaks.net/ircv3-site/software/servers.html), [libraries](http://danieloaks.net/ircv3-site/software/libraries.html)

**Comment by Mikaela** [comment]
Clients:
* I am not sure if ZNC is considered as supporting `server-time` because it's called as `znc.in/server-time-iso` in older than unreleased git versions.
* Is KVIrc considered as supporting SASL? As far as I am aware it supports only DH-\* in released versions and that again isn't so supported nowadays.
* WeeChat should have capital C.
* Kiwi IRC supports SASL, but has small issue https://github.com/prawnsalad/KiwiIRC/issues/674 .

**Comment by Mikaela** [comment]
Libraries

* I think Communi supports at least echo-message. *ping @jpnurmi*

**Comment by DanielOaks** [comment]
* Hmm, we could either mark it as yellow and `git only` or just leave it as is. @DarthGandalf , will ZNC be cutting a new release with the IRCv3 names soon?
* KVIrc also supports `plain`. Seems like a standard method allowed almost everywhere, but I haven't dealt with SASL much.
* Changed to WeeChat.
* I'll leave Kiwi as supported for now. They should fix that, but it does support SASL.

---

* The Communi library didn't have the string `echo-message` in its repo. The client has some handling code, but the library itself doesn't seem to have any support.

**Comment by DarthGandalf** [comment]
> will ZNC be cutting a new release with the IRCv3 names soon?

Yes, it will, though I don't have a date.

**Comment by DanielOaks** [comment]
Fair enough, will probably be fine to leave it as-is then. If you want me
to mark it yellow, let me know.

**Comment by Mikaela** [comment]
Could there be small comment/hover-over about it being named as `znc.in/server-time-iso` in older than git (to be replaced with actual version number)?

**Comment by jpnurmi** [comment]
http://communi.github.io/doc/dev/ircv3.html

**Comment by Mikaela** [comment]
Is there something currently blocking this? The matrix would be very helpful when linking people to http://ircv3.net/software/clients.html .

**Comment by DanielOaks** [comment]
I believe it's basically right to go (sorry, been a bit busy lately). I'll push it live tonight or tomorrow morning.

**Comment by TingPing** [comment]
@DanielOaks btw HexChat also supports Monitor and userhost-in-names

**Comment by DanielOaks** [comment]
@TingPing Updated.

This is now pushed to master. If there are any issues, please let us know.

**Comment by kaniini** [comment]
@DanielOaks Conspire supports SASL since always.

**Comment by TingPing** [comment]
Should conspire be listed at all, It's a dead project right?

**Comment by DanielOaks** [comment]
@kaniini Added SASL and multi-prefix for Conspire, since those seem to be the ones it requests (from browsing the source code).

**Comment by Mikaela** [comment]
> I'll leave Kiwi as supported for now. They should fix that, but it does support SASL.

The live version says that Kiwi doesn't support SASL.

**Comment by DanielOaks** [comment]
Silly me, that's fixed now. Thanks for letting me know.

**Comment by kaniini** [comment]
@TingPing well, probably not, but my point was that if they are going to bother to list it, they should at least list the details correctly.
