### ISSUE TITLE
Improve Specs page

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3.github.io#82]
I feel like we could make [this page](http://ircv3.net/irc/) quite a bit better.

Especially with the discussions we've been having about the merits of actually releasing features in batches (3.1, 3.2, 3.3, etc), it may be worth looking at different ways we could display the features.

One thing we can look at is the [IRCCloud page](https://blog.irccloud.com/ircv3/) describing the various IRCv3 features, and whether it'd be useful or appropriate for us to take a similar approach (presenting each spec with a short tagline describing what it accomplishes and giving a general overview of it). Depends on our audience and who we're targeting with the page, but I'll sketch out some ideas, and people can present their own in here.

**Comment by DanielOaks** [comment]
Yeah this has been on the pile for a while as something to look at. Anyone tackling this should probably take a look at https://github.com/ircv3/ircv3-specifications/issues/265 to see how that plays into this as well. Mockups are good here, feel free to throw them into this issue or PM them to dx or I.

**Comment by ChickenNuggers** [comment]
so with https://github.com/ircv3/ircv3-specifications/issues/265, should I just make it a list of specifications with a short description of each?

**Comment by DanielOaks** [comment]
I'm not too sure honestly. This is a weird issue to solve, since this essentially changes how we represent our specifications to people. Needs to be thought about fairly in-depth if we're overhauling it. That issue is useful because it also deals with changing how we present our specifications in general.

**Comment by ChickenNuggers** [comment]
I didn't really think about the other pages, honestly. I'm not too sure how it should be done with multiple pages besides having a list of (networks/clients/libraries/servers) that support the feature (optionally with a version beside it).

**Comment by DanielOaks** [comment]
yeah it's a bit annoying. I'd accept just overhauling the explicit specs page for now, and working out how to best display it on those other pages later. I might do up a rough mockup for this later otherwise.

**Comment by ChickenNuggers** [comment]
Alright, I'll work on that as soon as I poke the #! admins about listing our page on the participation.

**Comment by DanielOaks** [comment]
Something else to consider is the stuff discussed in #9. More specifically, around making sure that we gear this page properly, make it... relatively simple for regular users to see what we let them do, as well as linking to the specs for the peeps actually implementing it. IRCCloud blog post does this relatively well.

**Comment by DanielOaks** [comment]
This is done now \o/
