### ISSUE TITLE
mammon-ircd Status

### ISSUE THREAD

**Issue by r3c0d3x** [ircv3/ircv3.github.io#96]
Their website's [domain](http://www.mammon.io/) expired on [April 2nd](https://who.is/whois/mammon.io). Is this project dead, or have they simply just switched domains? [Their organization](https://github.com/mammon-ircd) also appears to be inactive (supporting the former position), with the last commit being made on January 30th.

If it is dead, we might want to remove it from this list (or maybe mark it as "Past Participants" or something): [participants.yml](https://github.com/ircv3/ircv3.github.io/blob/master/_data/participants.yml#L26)

**Comment by dequis** [comment]
The website was pretty much just an iframe to http://www.textfiles.com/underconstruction/ (warning: many gifs), so I'm not surprised they didn't bother renewing it.

The devs are still around and the code still exists implementing what's advertised in the software page.

**Comment by r3c0d3x** [comment]
Okay, just wanted to check up on it, thanks.
